export type ClipperRow = {
  rank: number;
  name: string;
  code: string;
  you?: boolean;
};

export const clippersRoster: ClipperRow[] = [
  { rank: 1, name: "9ZUNT", code: "9ZUNT" },
  { rank: 2, name: "Adam", code: "ADAM50" },
  { rank: 3, name: "Adem", code: "ADEM94" },
  { rank: 4, name: "Alex", code: "ZKKU" },
  { rank: 5, name: "Alex", code: "ALEX46" },
  { rank: 6, name: "Alex", code: "56E9J" },
  { rank: 7, name: "Alexis", code: "ALEXIS36" },
  { rank: 8, name: "amine", code: "AMINE" },
  { rank: 9, name: "amine", code: "KB3KJ" },
  { rank: 10, name: "amine", code: "AMINE97" },
  { rank: 11, name: "Amine", code: "AMINE2" },
  { rank: 12, name: "amir", code: "AMIR" },
  { rank: 13, name: "anthoninio", code: "JACKO35" },
  { rank: 14, name: "antoine", code: "ANTOINE40" },
  { rank: 15, name: "Artin", code: "ARTIN13" },
  { rank: 16, name: "Atkla", code: "ATKLA10" },
  { rank: 17, name: "Austeen", code: "AUSTEEN" },
  { rank: 18, name: "Aymen", code: "AYMEN" },
  { rank: 19, name: "Ayoub", code: "AYOUB62" },
  { rank: 20, name: "Bahtiyar", code: "BAHTIYAR90" },
  { rank: 21, name: "Bastien", code: "BASTIEN" },
  { rank: 22, name: "Bastien", code: "BASTIEN31" },
  { rank: 23, name: "Ben", code: "9GTUJ" },
  { rank: 24, name: "Bilal", code: "BILAL" },
  { rank: 25, name: "boss", code: "BOSS" },
  { rank: 26, name: "Bouyjil", code: "BOUJIL72" },
  { rank: 27, name: "Bryan", code: "BRYAN58" },
  { rank: 28, name: "Celien", code: "CELIEN18" },
  { rank: 29, name: "Chahder", code: "3BBED" },
  { rank: 30, name: "Chloé", code: "DEBLOAT" },
  { rank: 31, name: "Daryo", code: "DARYO48" },
  { rank: 32, name: "Daryo", code: "A4IJBV" },
  { rank: 33, name: "debloatfr", code: "DEBLOATFR" },
  { rank: 34, name: "dersha", code: "DERSHA" },
  { rank: 35, name: "Dyverside", code: "DYVERSIDE" },
  { rank: 36, name: "eloi", code: "ELOI46" },
  { rank: 37, name: "Emile", code: "EMILE" },
  { rank: 38, name: "Enzo", code: "ENZO71" },
  { rank: 39, name: "Eva", code: "EVA50" },
  { rank: 40, name: "Evro", code: "EVRO71", you: true },
  { rank: 41, name: "Ewabroer", code: "EWABROER98" },
  { rank: 42, name: "Florian", code: "FLORIAN91" },
  { rank: 43, name: "Florian", code: "FLORIAN52" },
  { rank: 44, name: "Foucault", code: "FOUCAULT16" },
  { rank: 45, name: "Gabriel", code: "GABRIEL43" },
  { rank: 46, name: "Gabriel", code: "N55PD" },
  { rank: 47, name: "Gabriel", code: "GABRIEL37" },
  { rank: 48, name: "Gene", code: "GENE48" },
  { rank: 49, name: "Giovani", code: "GIOVANI69" },
  { rank: 50, name: "Glowup", code: "GLOWUP14" },
  { rank: 51, name: "Grocervo", code: "GROCERVO23" },
  { rank: 52, name: "Guillaume", code: "GUILLAUME" },
  { rank: 53, name: "Hamdan", code: "HAMDAN" },
  { rank: 54, name: "Hamdan", code: "HAMDAN2" },
  { rank: 55, name: "hamdan", code: "hamdan" },
  { rank: 56, name: "hamdan", code: "hamdan3" },
  { rank: 57, name: "Hawky", code: "HAWKY" },
  { rank: 58, name: "Idir", code: "IDIR" },
  { rank: 59, name: "iehie", code: "IEHIE39" },
  { rank: 60, name: "Jawline Project", code: "JAWLINE" },
  { rank: 61, name: "Jen", code: "JEN25" },
  { rank: 62, name: "Jihed", code: "JIHED84" },
  { rank: 63, name: "Jim", code: "JIM14" },
  { rank: 64, name: "Joffrey", code: "9MKN9" },
  { rank: 65, name: "Jules", code: "JULES51" },
  { rank: 66, name: "Julien", code: "JULIEN30" },
  { rank: 67, name: "Julien", code: "JULIEN22" },
  { rank: 68, name: "Kais", code: "KAIS66" },
  { rank: 69, name: "Kevin", code: "KEVIN97" },
  { rank: 70, name: "Koda", code: "KODA" },
  { rank: 71, name: "kytox", code: "KYTOX" },
  { rank: 72, name: "leo", code: "LEO" },
  { rank: 73, name: "Louis", code: "LOUIS39" },
  { rank: 74, name: "Maél", code: "MAEL42" },
  { rank: 75, name: "mael", code: "mael" },
  { rank: 76, name: "Marwane", code: "MARWANE37" },
  { rank: 77, name: "Mathis", code: "MATHIS58" },
  { rank: 78, name: "Matteo", code: "S5M75" },
  { rank: 79, name: "max", code: "XP34E" },
  { rank: 80, name: "meysann", code: "MEYSANN36" },
  { rank: 81, name: "Mims", code: "MIMS47" },
  { rank: 82, name: "Mouadh", code: "DZ256" },
  { rank: 83, name: "Mouadh", code: "DZ253" },
  { rank: 84, name: "n", code: "NPRO" },
  { rank: 85, name: "Nabil", code: "NABIL96" },
  { rank: 86, name: "Nathan", code: "NATHAN" },
  { rank: 87, name: "Nico", code: "NICO53" },
  { rank: 88, name: "Noa", code: "NOA" },
  { rank: 89, name: "Nocti", code: "NOCTI64" },
  { rank: 90, name: "Nocti", code: "UYFMF" },
  { rank: 91, name: "Nolan", code: "NOLAN98" },
  { rank: 92, name: "Othman", code: "OTHMAN90" },
  { rank: 93, name: "Pierre", code: "PIERROT" },
  { rank: 94, name: "Pierre", code: "PIERRE50" },
  { rank: 95, name: "Presko", code: "PRESKO13" },
  { rank: 96, name: "qiangqiang", code: "QIANGQIANG72" },
  { rank: 97, name: "Rahim", code: "RAHIM23" },
  { rank: 98, name: "Rise", code: "B4JUN" },
  { rank: 99, name: "Rob", code: "ROB49" },
  { rank: 100, name: "Romain", code: "ROMAIN65" },
  { rank: 101, name: "Roman", code: "DMT9S" },
  { rank: 102, name: "Said", code: "SAID12" },
  { rank: 103, name: "Sam", code: "SAM" },
  { rank: 104, name: "Sam", code: "SAM2" },
  { rank: 105, name: "Sammy", code: "SAMMY40" },
  { rank: 106, name: "Samuel", code: "SAMUEL40" },
  { rank: 107, name: "Shax", code: "SHAX44" },
  { rank: 108, name: "Soufiane", code: "SOUFIANE55" },
  { rank: 109, name: "Soufiane", code: "SOUFIANE53" },
  { rank: 110, name: "SOULEK", code: "LEKS" },
  { rank: 111, name: "Super Glowup", code: "GLOWUP" },
  { rank: 112, name: "Teneoz", code: "TENEOZ20" },
  { rank: 113, name: "Thambir", code: "THAMBIR16" },
  { rank: 114, name: "Thao", code: "SHT8S" },
  { rank: 115, name: "ThatFitVibe", code: "THATFITVIBE" },
  { rank: 116, name: "Theo", code: "THEO" },
  { rank: 117, name: "Thomas", code: "THOMAS32" },
  { rank: 118, name: "thomas", code: "THOMAS92" },
  { rank: 119, name: "Thomas", code: "THOMAS26" },
  { rank: 120, name: "thomas", code: "THOMAS52" },
  { rank: 121, name: "Tristan", code: "TRISTAN44" },
  { rank: 122, name: "Tristan", code: "TRISTANDCT" },
  { rank: 123, name: "Wolf", code: "WOLF98" },
  { rank: 124, name: "Xx", code: "FIRST" },
  { rank: 125, name: "Xx", code: "GLOW" },
  { rank: 126, name: "Yasmine", code: "YASMINE97" },
  { rank: 127, name: "Yoann", code: "YOANN60" },
  { rank: 128, name: "Yuba", code: "YUBA" },
];

const palettes = [
  { bg: "#FEF3C7", fg: "#B45309" },
  { bg: "#E5E7EB", fg: "#4B5563" },
  { bg: "#FFEDD5", fg: "#C2410C" },
  { bg: "#DCFCE7", fg: "#15803D" },
  { bg: "#EDE9FE", fg: "#6D28D9" },
  { bg: "#DBEAFE", fg: "#1D4ED8" },
  { bg: "#FCE7F3", fg: "#BE185D" },
  { bg: "#CCFBF1", fg: "#0F766E" },
  { bg: "#FEE2E2", fg: "#B91C1C" },
  { bg: "#E0E7FF", fg: "#4338CA" },
];

export function clipperInitials(name: string) {
  const parts = name.trim().split(/\s+/);
  if (parts.length === 1) {
    const s = parts[0];
    if (s.length <= 2) return s.slice(0, 2).toUpperCase();
    return s.slice(0, 2).toUpperCase();
  }
  return (parts[0][0] + parts[1][0]).toUpperCase();
}

export function clipperColors(code: string) {
  let h = 0;
  for (const ch of code) h = (h + ch.charCodeAt(0) * 17) % palettes.length;
  return palettes[h];
}
